let textosCAT = [];
textosCAT = [
"VIII Torneig Pàdel CSNI",
"Data limiti - Fase de Lliga fins 2021.05.02",
"Informació",
"General",
"Notícies",
"Objectiu",
"El VIII Torneig de Pàdel de l'Centre Esportiu Nova Icària té com a objectiu fomentar la participació entre els socis de el club i la pràctica esportiva. L'organització és realitzada pels mateixos participants.",
"Normes de la competició",
"La inscripció és de 20 euros per parella (10 cada participant) que es destinaran a premis, íntegrament. El termini per abonar la inscripció és el 15 de febrer de 2021, inclusivament.",
"Format de el torneig",
"S'estableixen dos grups independents (A i B) sobre la base de la classificació de tornejos anteriors. A cada grup hi ha 4 subgrups (A1, A2, A3 i A4) que s'enfronten en mode lliga, de tots contra tots. Els 4 primers de cada grup passen a fase eliminatòria. Els partits els organitzen les parelles que s'enfronten, en horari i lloc a convenir per ells, respentando els terminis previstos. L'ordre de joc és indiferent. Es recomana obrir grups de whatsapp per coordinar les lliguetes.",
"Dates",
"FASE LLIGA fins a 2 de maig de 2021. <br /> FASE ELIMINATÒRIA fins a 30 de juny de 2021.",
"Premis",
"Guanyador i Finalista, i sorteig per a tots els que hagin jugat tots els partits.",
"APP",
"En aquesta aplicació podrà trobar informació actualitzada dels resultats i estadístiques de tots els partits.",
"Feedback",
"Si tens algun suggeriment o comentari sobre l'APP, o notes algun error en les dades, traducció o qualsevol altre, pots posar-te en contacte a través de Whatsapp i et estarem responent a la brevetat.",
"Contacte per Whatsapp",
"En aquesta secció s'aniran actualitzant les últimes notícies i anuncis de l'Torneig.",
"Incriptos",
"Grup A",
"Rànquing",
"Jugador",
"Grup B",
"Rànquing",
"Jugador",
"Estadístiques",
"Grups",
"Resultats",
"Posicions",
"Grup A1",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grup A2",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grup A3",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grup A4",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grup B1",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grup B2",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grup B3",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grup B4",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Posicions G-A1",
"Posicions G-A2",
"Posicions G-A3",
"Posicions G-A4",
"Posicions G-B1",
"Posicions G-B2",
"Posicions G-B3",
"Posicions G-B4",
"<span> G = </ span> Grup",
"<span> N ° = </ span> Posició en el grup",
"<span> ID = </ span> Identificador de la parella",
"<span> PJ = </ span> Partits jugats",
"<span> PG = </ span> Partits guanyats",
"<span> PP = </ span> Partits perduts",
"<span> SF = </ span> Quantitat de sets guanyats",
"<span> SC = </ span> Quantitat de sets perduts",
"<span> DS = </ span> Diferència a favor o en contra dels sets guanyats i perduts",
"Lliga",
"Grup A",
"Grup B",
"Vuitens",
"Quarts",
"Semifinal",
"Final"
];