let textosESP = [];
textosESP = [
"VIII Torneo Padel CSNI",
"Fecha limite - Fase de Liga hasta 02/05/2021",
"Informacion",
"General",
"Noticias",
"Objetivo",
"El VIII Torneo de Pádel del Centre Esportiu Nova Icària tiene como objetivo fomentar la participación entre los socios del club y la práctica deportiva. La organización es realizada por los propios participantes.",
"Normas de la competición",
"La inscripción es de 20 euros por pareja (10 cada participante) que se destinarán a premios, en su totalidad. El plazo para abonar la inscripción es el 15 de febrero de 2021, inclusive.",
"Formato del torneo",
"Se establecen dos grupos independientes (A y B) en base a la clasificación de torneos anteriores. En cada grupo hay 4 subgrupos (A1, A2, A3 y A4) que se enfrentan en modo liga, de todos contra todos. Los 4 primeros de cada grupo pasan a fase eliminatoria. Los partidos los organizan las parejas que se enfrentan, en horario y lugar a convenir por ellos, respentando los plazos previstos. El orden de juego es indiferente. Se recomienda abrir grupos de whatsapp para coordinar las liguillas.",
"Fechas",
"FASE LIGA hasta 2 de mayo de 2021.<br />FASE ELIMINATORIA hasta 30 de junio de 2021.",
"Premios",
"Ganador y Finalista, y sorteo para todos los que hayan jugado todos los partidos.",
"APP",
"En esta aplicación podrá encontrar información actualizada de los resultados y estadísticas de todos los partidos.",
"FeedBack",
"Si tienes alguna sugerencia o comentario sobre la APP, o notas algún error en los datos, traducción o cualquier otro, puedes ponerte en contacto a través de Whatsapp y te estaremos respondiendo a la brevedad.",
"Contacto por Whatsapp",
"En esta sección se irán actualizando las últimas noticias y anuncios del Torneo.",
"Incriptos",
"Grupo A",
"Ranking",
"Jugador",
"Grupo B",
"Ranking",
"Jugador",
"Estadisticas",
"Grupos",
"Resultados",
"Posiciones",
"Grupo A1",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grupo A2",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grupo A3",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grupo A4",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grupo B1",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grupo B2",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grupo B3",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Grupo B4",
"N°",
"ID",
"Jugador 1",
"Jugador 2",
"Posiciones G-A1",
"Posiciones G-A2",
"Posiciones G-A3",
"Posiciones G-A4",
"Posiciones G-B1",
"Posiciones G-B2",
"Posiciones G-B3",
"Posiciones G-B4",
"<span>G =</span> Grupo",
"<span>N° =</span> Posición en el grupo",
"<span>ID =</span> Identificador de la pareja",
"<span>PJ =</span> Partidos jugados",
"<span>PG =</span> Partidos ganados",
"<span>PP =</span> Partidos perdidos",
"<span>SF =</span> Cantidad de sets ganados",
"<span>SC =</span> Cantidad de sets perdidos",
"<span>DS =</span> Diferencia a favor o en contra de los sets ganados y perdidos",
"Cuadros",
"Grupo A",
"Grupo B",
"Octavos",
"Cuartos",
"Semifinal",
"Final"
];