let textosENG = [];
textosENG = [
"VIII Padel Tournament",
"Deadline - League Phase until 02/05/2021",
"Information",
"General",
"News",
"Objetive",
"The VIII Padel Tournament of the Center Esportiu Nova Icària aims to encourage participation among club members and sports practice. The organization is carried out by the participants themselves.",
"Competition rules",
"Registration is 20 euros per couple (10 each participant) that will go to prizes, in its entirety. The deadline to pay the registration is February 15, 2021, inclusive.",
"Tournament format",
"Two independent groups (A and B) are established based on the ranking of previous tournaments. In each group there are 4 subgroups (A1, A2, A3 and A4) that face each other in league mode, all against all. The first 4 of each group go to the knockout phase. The matches are organized by the couples that face each other, at a time and place to be agreed by them, respecting the established deadlines. The order of play is indifferent. It is recommended to open WhatsApp groups to coordinate the leagues.",
"Dates",
"LEAGUE PHASE until May 2, 2021. <br /> ELIMINATION PHASE until June 30, 2021.",
"Awards",
"Winner and Finalist, and raffle for everyone who has played all the games.",
"APP",
"In this application you can find updated information on the results and statistics of all the matches.",
"Feedback",
"If you have any suggestions or comments about the APP, or you notice any error in the data, translation or any other, you can get in touch through WhatsApp and we will be answering you as soon as possible.",
"Contact by Whatsapp",
"In this section the latest news and announcements of the Tournament will be updated.",
"Enrolled",
"Group A",
"Ranking",
"Player",
"B Group",
"Ranking",
"Player",
"Statistics",
"Groups",
"Results",
"Positions",
"Group A1",
"No.",
"ID",
"Player 1",
"Player 2",
"Group A2",
"No.",
"ID",
"Player 1",
"Player 2",
"Group A3",
"No.",
"ID",
"Player 1",
"Player 2",
"Group A4",
"No.",
"ID",
"Player 1",
"Player 2",
"Group B1",
"No.",
"ID",
"Player 1",
"Player 2",
"Group B2",
"No.",
"ID",
"Player 1",
"Player 2",
"Group B3",
"No.",
"ID",
"Player 1",
"Player 2",
"Group B4",
"No.",
"ID",
"Player 1",
"Player 2",
"G-A1 positions",
"G-A2 positions",
"G-A3 positions",
"G-A4 positions",
"G-B1 positions",
"G-B2 positions",
"G-B3 positions",
"G-B4 positions",
"<span> G = </span> Group",
"<span> N ° = </span> Position in the group",
"<span> ID = </span> Identifier of the pair",
"<span> PJ = </span> Games played",
"<span> PG = </span> Matches won",
"<span> PP = </span> Lost matches",
"<span> SF = </span> Number of sets won",
"<span> SC = </span> Number of lost sets",
"<span> DS = </span> Difference in favor or against the sets won and lost",
"League",
"A Group",
"B Group",
"Round of 16",
"Quarter finals",
"Semifinal",
"Final"
];